=== alexouuuuuuuuuuu/alexouuuuuuuuuuu.github.io/.astro/collections/works.schema.json
{
  "$ref": "#/definitions/works",
  "definitions": {
    "works": {
      "type": "object",
      "properties": {
        "id": {
          "type": "number"
        },
        "workName": {
          "type": "string"
        },
        "competences": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "photo": {
          "type": "string"
        },
        "date": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "workName",
        "competences",
        "photo",
        "date"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== alexouuuuuuuuuuu/alexouuuuuuuuuuu.github.io/src/content/data/works.json
[
  {
    "id": 1,
    "workName": "olive oil",
    "date": "16/09/2024",
    "competences": ["ui/ux design", "figma", "wireframing"],
    "photo": "/olive-oil.PNG"


  },
  {
    "id": 2,
    "workName": "cyberpong",
    "date": "20/12/2024",
    "competences": ["ui/ux design", "audiovisuel", "wireframing"],
    "photo": "/Glow-Pong.PNG"


  },
  {
    "id": 3,
    "workName": "daniel-wellington",
    "date": "06/02/2025",
    "competences": ["ui/ux design", "figma", "wireframing"],
    "photo": "/daniel-wellington.PNG"


  },
  {
    "id": 4,
    "workName": "bbbbb",
    "date": "16/09/2024",
    "competences": ["ui/ux design", "figma", "wireframing"],
    "photo": "olive-oil.PNG"


  }
]
